server:
  port: 3000
spring:
  application:
    name: nexus-account-service
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # flyway handles migrations
    properties:
      hibernate:
        format_sql: true